- Box.V2/Extensions/BoxResponseExtensions.cs
This is to address the issue #148 - Insufficient Exception Information When Status Code 403 / Forbidden
> Bubbled the exception details to client.(Issue #148)

- Box.V2/Managers/BoxSearchManager.cs
the current folder ids' is ignored because it not what is expected by the API. This fix addresses that issue
> fixed ancestor folder ids bug

- Box.V2/Request/HttpRequestHandler.cs
According to https://docs.box.com/reference#upload-a-file, the file bytes should come after the JSON for best performance.
> Fix multipart request form order

- Box.V2.JWTAuth/BoxJWTAuth.cs
Added a feature that allows using a userToken that was previously obtained by a call to the normal JWT Authentication mechanism. This allows a web-service to do the login with the full credentials - client programs can then call the web service to retrieve a token and then create a UserClient with only the userToken. That means the client has less sensitive data, and only gets access to a token that times out. Drawback is that the clients have to manage refreshing the access token.
> Allow creation of BoxJWTAuth objects without JWTPrivateKey and password

- Box.V2/Models/BoxRepresentationStatus.cs
I was working with representations endpoint and found that the status of the representation is always null. I Inspected the endpoint with fiddler and realized that the response contains a property called 'state' where the BoxRepresentationStatus class has defined it as 'Status'. So i went ahead and renamed property name to 'State' and the Json property name to 'state' accordingly.
> Modified 'Status' property of the BoxRepresentationStatus class to overcome deserialization issue

- Box.V2.Core/Box.V2.Core.csproj
For some reason, the `dotnet` tool we use for release won't use the values in the nuspec file unless it's explicitly mentioned in the csproj file.  Adding this ensures that the package metadata for the Box.V2.Core project will be present in the nuget package.
> Help build tools find Box.V2.Core nuspec file

- Box.V2.Test/BoxUsersManagerTest.cs
- Box.V2/Box.V2.csproj
- Box.V2/Models/BoxTrackingCode.cs
- Box.V2/Models/BoxUser.cs
- Box.V2/Models/Request/BoxUserRequest.cs
Moving the original change by @allenmichael to a feature branch in the SDK proper so CI tests pass.  Fixes #424
> Fix parsing for user tracking codes

- Box.V2/Request/HttpRequestHandler.cs
Setting both `Tlsv11` and `Tlsv12` causes an error in .NET Core on MacOS — switching to just one or the other appears to resolve the issue.  Since TLSv1.2 is the preferred version, we will set that one to maximize security going forward.
> Fix protocol not supported error in .NET Core on MacOS

- Box.V2.Test/BoxFilesManagerTest.cs
- Box.V2/Managers/BoxFilesManager.cs
- Made file name nullable when uploading new version, since the API considers the parameter optional
- Corrected the upload method to actually send the `attributes` part with the new file name
- Added the `contentModifiedTime` parameter to the method to set the file timestamp on upload
Fixes #496
> Fix file rename on new version upload

- Box.V2.Test/BoxWebLinksManagerTest.cs
- Box.V2/Managers/BoxFilesManager.cs
- Box.V2/Managers/BoxWebLinksManager.cs
Added `client.WebLinksManager.CopyAsync(...)`, `client.WebLinksManager.CreateSharedLinkAsync(...)`, and `client.WebLinksManager.DeleteSharedLinkAsync(...)` methods to expose missing web link functionality.
Fixes #526
> Add support for missing Web Link methods

- Box.V2/Models/BoxGroupEventSource.cs
- Box.V2/Models/BoxGroupFileCollaborationEventSource.cs
- Box.V2/Models/BoxGroupFolderCollaborationEventSource.cs
- Box.V2/Models/BoxUserFileCollaborationEventSource.cs
- Box.V2/Models/BoxUserFolderCollaborationEventSource.cs
Many of the EventSource classes defined an `Id` property which shadows the base `BoxEntity` property of the same name.  Without marking the subclass property as `override`, the data exposed would vary depending on how the object was cast.  Marking the property as `override` should ensure that the correct data is always exposed.
Fixes #535
> Override Id property in EventSource classes

- Box.V2.Test/BoxTasksManagerTest.cs
- Box.V2/Models/BoxTaskAssignment.cs
The `resolution_state` field of a task assignment can inadvertently contain localized text, which breaks the automatic deserialization into an enum and will throw as soon as the object is created.  The current enum solution seems too brittle, so it has been deprecated in favor of two new `string` properties: `.StatusTranslated` for the localized text and `.Status` for the new `status` field that will only contain the enum string values.  The deprecated `.ResolutionState` property has been re-implemented to convert to enum from the `status` field, which should prevent it from throwing on instantiation while maintaining backward compatibility.
Fixes #529
> Fix deserialization of translated task assignment status

- Box.V2.Test/BoxEventsManagerTest.cs
- Box.V2.Test/BoxSearchManagerTest.cs
- Box.V2/Config/Constants.cs
- Box.V2/Managers/BoxEventsManager.cs
- Box.V2/Managers/BoxFilesManager.cs
- Box.V2/Managers/BoxSearchManager.cs
The previous fix to encode all query parameters caused some one-off places where query parameters were already being encoded to double-encode.  These one-off encodings have been removed, and tests added to ensure the encoding is correct.  Additionally the date format string constant has been updated to align with the format returned by the API, and places I found using bespoke date format strings have been updated to reference the constant instead.
Fixes #561
> Fix date encoding in query parameters

- docs/authentication.md
- docs/collaboration-whitelist.md
- docs/collaborations.md
- docs/collections.md
- docs/comments.md
- docs/device-pins.md
- docs/files.md
- docs/groups.md
- docs/legal-holds.md
- docs/metadata-cascade-policies.md
- docs/metadata.md
- docs/recent-items.md
- docs/retention-policies.md
- docs/search.md
- docs/storage-policies.md
- docs/tasks.md
- docs/terms-of-service.md
- docs/trash.md
- docs/users.md
- docs/watermarking.md
- docs/web-links.md
- docs/webhooks.md
I've tagged the majority of code samples to an endpoint for usage in the new developer documentation.
> Tag code samples for usage in developer docs

- Box.V2/Models/BoxTrackingCode.cs
This is intended to allow creation of codes for use in BoxUserRequests, but still leave BoxUser.TrackingCodes immutable.
Closes #593
> Add constructor for BoxTrackingCode 

- Box.V2/Managers/BoxUsersManager.cs
- Box.V2/Models/BoxUser.cs
- already part of the BoxUserRequest object, and now it should be possible to pull this back in a user object if it is possible to set it in a request for creation or update.
> Add ExternalAppUserId property to BoxUser model

- Box.V2.Test.Integration/BoxMetadataManagerTestIntegration.cs
- Box.V2.Test.Integration/BoxResourceManagerTestIntegration.cs
- Box.V2.Test/BoxMetadataManagerTest.cs
- Box.V2/Managers/BoxMetadataManager.cs
- Box.V2/Managers/BoxResourceManager.cs
The `Metadata.ExecuteMetadataQueryAsync()` method was not correctly serializing the POST body when `queryParameters` or `orderBy` parameters were passed. Also, the method was not adding the JSON content type header. Both were fixed.
> Fixed metadata query

- Box.V2.Test/BoxUsersManagerTest.cs
- Box.V2/Box.V2.csproj
`BoxNotificationEmail` and `BoxNotificationEmailField` were not added to the `.csproj` file, so they were not accessible in the SDK. This PR fixes this issue by adding them to the `.csproj` file.
> Fix Box notification email field

- Box.V2/Request/HttpRequestHandler.cs
- CHANGELOG.md
When a user calls `BoxJWT.AdminToken()` to get a token in a UI element, a deadlock issue will occur because the underlying async request methods in `HttpRequestHandler.cs` don't have `Configure.await(false)` appended to them. This PR is in regards to this issue (#638).
Why this is a fix is detailed in this [article](https://medium.com/bynder-tech/c-why-you-should-use-configureawait-false-in-your-library-code-d7837dce3d7f).
> Fix deadlock issue for JWT Auth in UI elements

- Box.V2.Test/BoxRequestTest.cs
- Box.V2/Wrappers/BoxRequest.cs
- CHANGELOG.md
Sanitizes path parameters when constructing a URI. If the path contains relative paths such as `/../`, an error will be thrown.
> Add path parameter sanitization

- Box.V2/Box.V2.csproj
- Box.V2/Config/BoxConfig.cs
- Box.V2/Config/Constants.cs
The endpoint for creating upload sessions for new file versions was using version 2.1 of the API. Every other endpoint used version 2.0 of the API. This PR changed the endpoint from 2.1 to 2.0. The admin experience team said both versions of the API call the same PHP code in the monolith and are not different in any way. A similar change was made for the upload session endpoint for new files in PR #287.
> Change API version used for creating upload sessions for new file versions

- .github/workflows/releases.yml
- Box.V2.Test.Integration/BoxFilesManagerTestIntegration.cs
- Box.V2.Test.Integration/BoxFoldersManagerTestIntegration.cs
- Box.V2/Managers/BoxFoldersManager.cs
- Box.V2/Managers/BoxUsersManager.cs
Add ability to set a request timeout for `FoldersManager.UpdateInformationAsync` and `UsersManager.MoverUserFolderAsync`
> Add ability to set a request timeout when updating folder information and moving a user's folder

- Box.V2/JWTAuth/BoxJWTAuth.cs
Fixes a bug discovered in #645 and #693 where we were not properly reading the error code and description from the exception thrown for an expired claim ("clock skew").
This bug was preventing any requests to be retried and from returning the actual expired claim exception to the client.
Now that retries should occur properly when there is "clock skew" between the client and server, the JWT assertion should be created using the Box server time found in the response headers, which should result in a successful authentication on the first retry.
> Fix auth retry for expired claim

- Box.V2.Test/BoxFilesManagerTest.cs
- Box.V2.Test/TestData/smalltest.pdf
- Box.V2/Box.V2.csproj
- Box.V2/Config/BoxConfig.cs
- Box.V2/Config/Constants.cs
- Box.V2/Config/IBoxConfig.cs
- Box.V2/Converter/BoxZipConflictConverter.cs
- Box.V2/Managers/BoxFilesManager.cs
- Box.V2/Models/BoxZip.cs
- Box.V2/Models/BoxZipConflict.cs
- Box.V2/Models/BoxZipConflictItem.cs
- Box.V2/Models/BoxZipDownloadStatus.cs
- Box.V2/Models/Request/BoxZipItemRequest.cs
- Box.V2/Models/Request/BoxZipRequest.cs
- Box.V2/Models/Request/BoxZipRequestItem.cs
- CHANGELOG.md
- docs/files.md
Added the ability to create a zip file in Box and download it. Wrote a unit test and manually tested it.
> Add zip functionality

- Box.V2.Samples.Core.AppUser.Create/Program.cs
- Box.V2.Samples.Core.File.Upload/Program.cs
- Box.V2.Samples.Core.HttpProxy/Program.cs
- Box.V2.Samples.JWTAuth/Program.cs
- Box.V2.Samples.TransactionalAuth/Program.cs
- Box.V2.Test.Integration/BoxAuthTestIntegration.cs
- Box.V2.Test.Integration/BoxConfigTestIntegration.cs
- Box.V2.Test.Integration/BoxFoldersManagerTestIntegration.cs
- Box.V2.Test.Integration/BoxResourceManagerTestIntegration.cs
- Box.V2.Test.Integration/BoxTokenExchangeTestIntegration.cs
- Box.V2.Test/AuthRepositoryTest.cs
- Box.V2/Box.V2.csproj
- Box.V2/Config/BoxConfig.cs
- Box.V2/Config/BoxConfigBuilder.cs
- Box.V2/Config/IBoxConfig.cs
- Box.V2/JWTAuth/BoxJWTAuth.cs
- CHANGELOG.md
- README.md
- docs/authentication.md
I created BoxConfigBuilder to make it easier to create new BoxConfig (fluent builder, used in [.NET Core](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.configurationbuilder?view=dotnet-plat-ext-5.0) to build configuration so .NET devs should be familiar with this). 
At the same time BoxConfig was made immutable. I could also remove constructors from BoxConfig, but it would make it more 'breaking' that it is at the moment. To be discussed.
> Add BoxConfigBuilder and make BoxConfig immutable

- .editorconfig
- Box.V2/Auth/AuthRepository.cs
- Box.V2/Managers/BoxCollaborationWhitelistManager.cs
- Box.V2/Managers/BoxDevicePinManager.cs
- Box.V2/Managers/BoxFilesManager.cs
- Box.V2/Managers/BoxFoldersManager.cs
- Box.V2/Managers/BoxGroupsManager.cs
- Box.V2/Managers/BoxLegalHoldPoliciesManager.cs
- Box.V2/Managers/BoxMetadataCascadePolicyManager.cs
- Box.V2/Managers/BoxMetadataManager.cs
- Box.V2/Managers/BoxRecentItemsManager.cs
- Box.V2/Managers/BoxRetentionPoliciesManager.cs
- Box.V2/Managers/BoxSignRequestsManager.cs
- Box.V2/Managers/BoxStoragePoliciesManager.cs
- Box.V2/Managers/BoxUsersManager.cs
- Box.V2/Managers/BoxWebhooksManager.cs
- Box.V2/Utility/Retry.cs
> fix: add missing configureAwait(false) when awaiting to prevent deadlocks

- Box.V2/Exceptions/BoxAuthenticationFailedException.cs
- Box.V2/Exceptions/BoxException.cs
Fix for https://github.com/box/box-windows-sdk-v2/issues/788
> fix: Creating BoxAuthenticationFailedException no longer throws an exception

- Box.V2.Test/BoxUsersManagerTest.cs
- Box.V2/Box.V2.csproj
- Box.V2/Models/Request/BoxUserRolloutRequest.cs
> fix: correctly pass null when rolling out user from the enterprise

- Box.V2.Test/BoxCCGAuthTest.cs
- Box.V2.Test/CCGAuthRepositoryTest.cs
- Box.V2.Test/Extensions/DictionaryExtensions.cs
- Box.V2/Box.V2.csproj
- Box.V2/CCGAuth/BoxCCGAuth.cs
- Box.V2/CCGAuth/CCGAuthRepository.cs
- Box.V2/Config/BoxConfigBuilder.cs
- Box.V2/Config/Constants.cs
> feat: add Client Credentials Grant auth support

- Box.V2.Test.Integration/BoxFilesManagerIntegrationTest.cs
- Box.V2.Test.Integration/Configuration/Commands/ICommand.cs
- Box.V2.Test.Integration/Configuration/Commands/NonDisposableCommands/CreateNewFileVersion.cs
- Box.V2.Test.Integration/Configuration/IntegrationTestBase.cs
- Box.V2.Test/Box.V2.Test.csproj
- Box.V2.Test/BoxFilesManagerTest.cs
- Box.V2.Test/Fixtures/BoxFiles/ViewVersions200.json
- Box.V2/Models/BoxFileVersion.cs
> feat: add `version_number` to `BoxFileVersion`

- .github/workflows/build_and_test.yml
- Box.V2.Test/Box.V2.Test.csproj
- Box.V2.Test/BoxFilesManagerTest.cs
- Box.V2.Test/BoxFoldersManagerTest.cs
- Box.V2.Test/BoxJWTAuthTest.cs
- Box.V2.Test/BoxResourceManagerTest.cs
- Box.V2.Test/Helpers/InstantRetryStrategy.cs
- Box.V2.Test/RetryStrategyTest.cs
- Box.V2/Box.V2.csproj
- Box.V2/JWTAuth/BoxJWTAuth.cs
- Box.V2/Utility/ExponentialBackoff.cs
- Box.V2/Utility/IRetryStrategy.cs
I also refactored exponential backoff test to speed it up considerably.
Tests in core against different runtimes are in a single job, as this is faster than multiple ones.
> chore: run tests under all supported major netcore versions

- Box.V2.Test.Integration/BoxFilesManagerIntegrationTest.cs
- Box.V2.Test.Integration/BoxWebLinkManagerIntegrationTest.cs
- Box.V2.Test.Integration/Configuration/IntegrationTestBase.cs
- Box.V2.Test/Box.V2.Test.csproj
- Box.V2.Test/BoxFilesManagerTest.cs
- Box.V2.Test/BoxFoldersManagerTest.cs
- Box.V2.Test/BoxWebLinksManagerTest.cs
- Box.V2.Test/Fixtures/BoxFiles/CreateFileSharedLink200.json
- Box.V2.Test/Fixtures/BoxFolders/CreateFolderSharedLink200.json
- Box.V2.Test/Fixtures/BoxWebLinks/CreateWebLinkSharedLink200.json
- Box.V2/Extensions/BoxExtensions.cs
- Box.V2/Managers/BoxFoldersManager.cs
- Box.V2/Managers/BoxWebLinksManager.cs
- Box.V2/Models/BoxPermission.cs
- Box.V2/Models/Request/BoxPermissionsRequest.cs
- Box.V2/Models/Request/BoxSharedLinkRequest.cs
I decided to model the SDK like open-api (can-edit for File, Folder and WebLink). An exception is thrown when you try to set `can_edit` `true` for Folder or WebLink. The API throws an exception when you do this, so we can throw it earlier.
Another possible solution would be to either separate SharedLink for File, Folder, and WebLink (a breaking change), or deprecate the existing methods in favor of new ones with new DTOs.
> feat: add `can_edit` field to `SharedLink`

- Box.V2.Test/Box.V2.Test.csproj
- Box.V2.Test/BoxFilesManagerTest.cs
- Box.V2.Test/BoxResourceManagerTest.cs
- Box.V2.Test/Fixtures/BoxFiles/GetRepresentationContentPending200.json
- Box.V2.Test/Fixtures/BoxFiles/PollRepresentationPending200.json
- Box.V2/Config/BoxConfig.cs
- Box.V2/Config/BoxConfigBuilder.cs
- Box.V2/Config/IBoxConfig.cs
- Box.V2/Managers/BoxFilesManager.cs
Fixed infinite loop retries. We now use exponential backoff strategy like in the rest of the SDK. I also exposed `IRetryStrategy` that is used in tests for now.
> fix: replace infinite retries with exponential backoff strategy in file representations

- .github/semantic.yml
- .github/workflows/semantic-pr.yml
Using https://github.com/amannn/action-semantic-pull-request. Using `pull_request_target` trigger, so it will be run after the merge.
> chore: replace semantic validation bot with action

- Box.V2/Managers/BoxResourceManager.cs
- Box.V2/Request/HttpRequestHandler.cs
If runtime version cannot be determined from assembly or in case of Blazor use the preferred way to get runtime version introduced in .net core 3.0
Also added check for AutomaticDecompression settings for HttpHandler, because it's not supported in Blazor at the moment.
> fix: fix null reference exception when it's not possible to get `runtime` version from the assembly

- Box.V2.Test/BoxCCGAuthTest.cs
- Box.V2/CCGAuth/BoxCCGAuth.cs
- Box.V2/CCGAuth/CCGAuthRepository.cs
- Box.V2/Managers/BoxResourceManager.cs
- docs/authentication.md
> feat: `BoxCCGAuth` add User and Admin clients factory methods without initial token

- Box.V2.Test.Integration/BoxRetentionPolicyManagerIntegrationTest.cs
- Box.V2.Test.Integration/Configuration/Commands/DisposableCommands/CreateRetentionPolicyCommand.cs
- Box.V2.Test.Integration/Configuration/IntegrationTestBase.cs
- Box.V2.Test/Box.V2.Test.csproj
- Box.V2.Test/BoxMetadataManagerTest.cs
- Box.V2.Test/Fixtures/BoxMetadata/CreateMetadataTemplate200.json
- Box.V2/Models/BoxMetadataTemplate.cs
- Box.V2/Models/BoxRetentionPolicyAssignment.cs
- Box.V2/Models/Request/BoxRetentionPolicyAssignmentRequest.cs
Add `Id` to `MetadataTemplateField`
Fix usage of `start_date_field` in `BoxRetentionPolicyAssignment`
> feat: add `Id` to `MetadataTemplateField`

- docs/files.md
Add .Net example to https://developer.box.com/reference/get-zip-downloads-id-content/
> docs: Add ZIP downloads sample tab

- Box.V2/JWTAuth/BoxJWTAuth.cs
> fix: Use fixed value of `aud` field in `JWT` claim

- Box.V2/Managers/BoxResourceManager.cs
> fix: Catch all exceptions when getting `User Agent` header

- Box.V2/Managers/BoxResourceManager.cs
> fix: catch exception when .net core version cannot be determined

- Box.V2/Box.V2.csproj
- Box.V2/packages.config
Replace deprecated BouncyCastle.Crypto with BouncyCastle.Cryptography
> fix: replace deprecated `BouncyCastle`

- Box.V2/Models/BoxSignRequestSigner.cs
Fixes #912 
Same as in the spec: https://developer.box.com/reference/resources/sign-request/#param-signers-inputs-content_type
> feat: add `attachment` content type to `SignRequestSigner`

- Box.V2.Core/Box.V2.Core.csproj
- Box.V2/Box.V2.nuspec
- Box.V2/Utility/AssemblyInfo.cs
- CHANGELOG.md
Bumping version files for the next release! v5.6.1
> chore: release v5.6.1

- Box.V2/Box.V2.csproj
- Box.V2/Utility/ExponentialBackoff.cs
- Box.V2/Utility/ThreadSafeRandom.cs
On .NET Framework it is incorrect to recreate Random instances each time, these should instead be one per instance. On .NET Core and later this is not a limitation, but the libraries share a codebase.
Fixes #944
> fix: do not recreate Random each time

- Box.V2.Test.Integration/BoxFolderManagerIntegrationTest.cs
- Box.V2/Models/BoxEnums.cs
> fix: Add missing enum values to `BoxSortBy`

- .gitattributes
- Box.V2.Core/Box.V2.Core.csproj
- Box.V2/Box.V2.csproj
- Box.V2/Utility/ContentTypeMapper.cs
Fixes #959 and #903 
Modified `.gitattributes` file due to the rule in `.editorconfig` for line endings of .cs file
> fix: remove `Microsoft.AspNetCore.StaticFiles` and `System.Web` dependencies
