box/box-windows-sdk-v2

Box.V2.Test.Integration/BoxFoldersManagerTestIntegration.cs, Box.V2.Test.Integration/BoxResourceManagerTestIntegration.cs, Box.V2/Box.V2.csproj, Box.V2/Managers/BoxFilesManager.cs, Box.V2/Managers/BoxFoldersManager.cs, Box.V2/Models/BoxPermission.cs, Box.V2/Models/Request/BoxDeleteSharedLinkRequest.cs, Box.V2/Models/Request/BoxPermissionsRequest.cs
* Fixed shared link request passing the wrong parameter
* Merged JogyBlack's pull request
* Integration test coverage
=> Shared link

Box.V2/Managers/BoxUsersManager.cs
- Included method for deleting users
- Fixed UpdateUserInformationAsync method as it wasn't using the correct http verb as documented in the API @ https://developers.box.com/docs/#users-update-a-users-information
=> Included method for deleting users & Fixed UpdateUserInformationAsync method

Box.V2.Samples.JWTAuth/Program.cs, Box.V2/Box.V2.csproj, Box.V2/BoxClient.cs, Box.V2/Config/BoxConfig.cs, Box.V2/Config/Constants.cs, Box.V2/Config/IBoxConfig.cs, Box.V2/Converter/BoxItemConverter.cs, Box.V2/Managers/BoxRetentionPoliciesManager.cs, Box.V2/Models/BoxCollection.cs, Box.V2/Models/BoxEntity.cs, Box.V2/Models/BoxFileVersionRetention.cs, Box.V2/Models/BoxRetentionAssignment.cs, Box.V2/Models/BoxRetentionPolicy.cs, Box.V2/Models/BoxRetentionPolicyAssignment.cs, Box.V2/Models/BoxSortOrder.cs, Box.V2/Models/BoxUser.cs, Box.V2/Models/Request/BoxFileVersionRetentionRequest.cs, Box.V2/Models/Request/BoxRequestEntity.cs, Box.V2/Models/Request/BoxRetentionPolicyAssignmentRequest.cs, Box.V2/Models/Request/BoxRetentionPolicyRequest.cs, Box.V2/Models/Request/BoxUserRequest.cs
added support for Box Retention Policies.
=> Retention policy support

Box.V2/Box.V2.csproj, Box.V2/Config/Constants.cs, Box.V2/Converter/BoxJsonConverter.cs, Box.V2/Managers/BoxSearchManager.cs, Box.V2/Models/Request/BoxMetadataFilterRequest.cs, Box.V2/Models/Request/BoxRequestEntity.cs
adds support for all advanced search parameters, including metadata search
=> Advanced search

Box.V2.Samples.JWTAuth/Program.cs, Box.V2/BoxClient.cs, Box.V2/Config/Constants.cs, Box.V2/Extensions/BoxResponseExtensions.cs, Box.V2/Managers/BoxCollaborationsManager.cs, Box.V2/Managers/BoxCommentsManager.cs, Box.V2/Managers/BoxFilesManager.cs, Box.V2/Managers/BoxFoldersManager.cs, Box.V2/Managers/BoxGroupsManager.cs, Box.V2/Managers/BoxResourceManager.cs, Box.V2/Managers/BoxRetentionPoliciesManager.cs, Box.V2/Managers/BoxSearchManager.cs, Box.V2/Managers/BoxUsersManager.cs, Box.V2/Request/HttpRequestHandler.cs, Box.V2/Wrappers/BoxRequest.cs, Box.V2/Wrappers/BoxResponse.cs, Box.V2/Wrappers/Contracts/IBoxRequest.cs
added method to get the direct Uri of a file;
also added support for As-User
=> Download url

Box.V2/Managers/BoxRetentionPoliciesManager.cs, Box.V2/Models/BoxRetentionPolicy.cs, Box.V2/Models/Request/BoxRetentionPolicyRequest.cs
added missing 'Async' to some methods;
made RetentionLength property nullable for request;
made RetentionLength a string in response class because Box will return either an int or a string;
=> Retention Policy bug fixes

Box.V2/Box.V2.csproj, Box.V2/BoxClient.cs, Box.V2/Config/BoxConfig.cs, Box.V2/Config/Constants.cs, Box.V2/Config/IBoxConfig.cs, Box.V2/Converter/BoxItemConverter.cs, Box.V2/Managers/BoxEventsManager.cs, Box.V2/Models/BoxCollection.cs, Box.V2/Models/BoxEnterpriseEvent.cs, Box.V2/Models/BoxFileEventSource.cs
Adds support for retrieving Enterprise Events
=> Enterprise events

Box.V2/Box.V2.csproj, Box.V2/Managers/BoxFilesManager.cs, Box.V2/Models/BoxPreflightCheck.cs
Adds support for accessing the data returned from pre-flight check
=> Pre flight upload url

Box.V2/Box.V2.csproj, Box.V2/BoxClient.cs, Box.V2/Config/BoxConfig.cs, Box.V2/Config/Constants.cs, Box.V2/Config/IBoxConfig.cs, Box.V2/Converter/BoxItemConverter.cs, Box.V2/Managers/BoxWebhooksManager.cs, Box.V2/Models/BoxCollection.cs, Box.V2/Models/BoxWebhook.cs, Box.V2/Models/Request/BoxWebhookRequest.cs
adds support for creating, updating, deleting, and listing webhooks V2
=> Webhooks v2

Box.V2/Managers/BoxFilesManager.cs
=> Get File's Comments

Box.V2/Managers/BoxFoldersManager.cs
=> Copy Folder

Box.V2/Managers/BoxCollaborationsManager.cs
Adding and reorganizing comments
=> Get Collaboration

Box.V2.JWTAuth/BoxJWTAuth.cs, Box.V2.JWTAuth/JWTAuthRepository.cs
=> JWT (app user)

Box.V2/Auth/AuthRepository.cs, Box.V2/Models/OAuthSession.cs
=> OAuth 2 (managed user)

Box.V2.Test/BoxFoldersManagerTest.cs, Box.V2/Managers/BoxFoldersManager.cs
Adding comments, adding unit test PurgeTrashedFolder_ValidResponse_FolderDeleted
=> Permanently Delete

Box.V2/Managers/BoxFoldersManager.cs
=> Get Trashed Folder

Box.V2/Managers/BoxFilesManager.cs
Updating comments, validate implementation and unit test
=> Restore Item

Box.V2.Test/BoxFilesManagerTest.cs, Box.V2/Managers/BoxFilesManager.cs
Adding comments for inputs and return. Adding unit test  GetEmbedLink_ValidResponse_ValidEmbedLink for validation of embed link
=> Get Embed Link

Box.V2/Managers/BoxFilesManager.cs
Adding comments for GetTrashedAsync
=> Get Trashed File

Box.V2.Test/BoxCollaborationsManagerTest.cs, Box.V2.Test/BoxResourceManagerTest.cs, Box.V2/Config/Constants.cs, Box.V2/Managers/BoxCollaborationsManager.cs
Adding method GetPendingCollaborationAsync with comments, adding unit test GetPendingCollaboration_ValidResponse_ValidEntries
=> Pending Collaborations

Box.V2.Test/BoxFilesManagerTest.cs, Box.V2.Test/BoxResourceManagerTest.cs, Box.V2/Managers/BoxFilesManager.cs
Changing implementation for DownloadStreamAsync, adding unit test DownloadStream_ValidResponse_ValidStream
=> DownloadStream

Box.V2.Test/BoxFilesManagerTest.cs, Box.V2/Box.V2.csproj, Box.V2/Config/Constants.cs, Box.V2/Converter/BoxItemConverter.cs, Box.V2/Managers/BoxFilesManager.cs, Box.V2/Models/BoxTask.cs
Adding implementation for GetFileTasks, adding unit test GetFileTasks_ValidResponse_ValidTasks
=> Get File's Tasks

Box.V2/Managers/BoxSearchManager.cs
=> Advanced Search, Search for query

Box.V2.Test/BoxFilesManagerTest.cs, Box.V2/Managers/BoxFilesManager.cs, Box.V2/Models/BoxFileLock.cs, Box.V2/Models/Request/BoxFileLockRequest.cs
Adding comments, extending request object, verifying implementation
UpdateFileLock_ValidResponse_ValidFile
=> Lock and Unlock

Box.V2.Test/BoxFilesManagerTest.cs, Box.V2/Managers/BoxFilesManager.cs, Box.V2/Models/BoxPreflightCheck.cs
Adding comments to PreflightCheck, writing unit test PreflightCheck_ValidResponse_ValidStatus
=> Preflight Check

Box.V2.Test/BoxFilesManagerTest.cs, Box.V2/Managers/BoxFilesManager.cs
Adding comments for input params, adding unit test GetThumbnail_ValidResponse_ValidStream
=> Get Thumbnail

Box.V2.Test/BoxFoldersManagerTest.cs, Box.V2/Managers/BoxFoldersManager.cs
Adding comments, adding unit test
=> Get Trashed Items

Box.V2.Test/Box.V2.Test.csproj, Box.V2.Test/BoxSharedItemsManagerTest.cs, Box.V2/Box.V2.csproj, Box.V2/BoxClient.cs, Box.V2/Config/BoxConfig.cs, Box.V2/Config/Constants.cs, Box.V2/Config/IBoxConfig.cs, Box.V2/Managers/BoxSharedItemsManager.cs
Adding BoxSharedItemsManager, adding BoxSharedItemsManagerTest
=> Shared Items

Box.V2.Test/Box.V2.Test.csproj, Box.V2.Test/BoxCollectionsManagerTest.cs, Box.V2/Box.V2.csproj, Box.V2/Config/BoxConfig.cs, Box.V2/Config/Constants.cs, Box.V2/Config/IBoxConfig.cs, Box.V2/Converter/BoxItemConverter.cs, Box.V2/Managers/BoxCollectionsManager.cs, Box.V2/Models/BoxCollectionItem.cs, Box.V2/Models/Request/BoxCollectionsRequest.cs
Adding methods, comments and unit tests
=> Create or Delete, Get Collections, Get Collection Items

Box.V2.Test.Integration/Box.V2.Test.Integration.csproj, Box.V2.Test.Integration/BoxWebhooksManagerTestIntegration.cs, Box.V2.Test/Box.V2.Test.csproj, Box.V2.Test/app.config, Box.V2/Box.V2.csproj, Box.V2/Managers/BoxWebhooksManager.cs, Box.V2/Models/Request/BoxWebhookRequest.cs, Box.V2/packages.config
added comments and integration tests for webhooks v2;
also added webhook validation method that depends on BouncyCastle-PCL library
=> Webhooks v2 review

Box.V2.Test/BoxCommentsManagerTest.cs, Box.V2/Managers/BoxCommentsManager.cs, Box.V2/Models/Request/BoxCommentRequest.cs
Updating comments, adding unit tests
=> Comments management

Box.V2.Test/Box.V2.Test.csproj, Box.V2.Test/BoxTasksManagerTest.cs, Box.V2/Box.V2.csproj, Box.V2/Config/BoxConfig.cs, Box.V2/Config/Constants.cs, Box.V2/Config/IBoxConfig.cs, Box.V2/Converter/BoxItemConverter.cs, Box.V2/Managers/BoxTasksManager.cs, Box.V2/Models/BoxEnums.cs, Box.V2/Models/BoxTaskAssignment.cs, Box.V2/Models/Request/BoxAssignmentRequest.cs, Box.V2/Models/Request/BoxTaskAssignmentRequest.cs, Box.V2/Models/Request/BoxTaskAssignmentUpdateRequest.cs, Box.V2/Models/Request/BoxTaskRequest.cs
Adding methods, comments, unit tests
=> Create, Update, Get, Delete Task Assignment

Box.V2.Test.Integration/Box.V2.Test.Integration.csproj, Box.V2.Test.Integration/BoxEventsManagerTestIntegration.cs, Box.V2/Managers/BoxEventsManager.cs, Box.V2/Models/BoxEnterpriseEvent.cs, Box.V2/Models/BoxEnums.cs
=> Events review

Box.V2.Samples.TransactionalAuth/App.config, Box.V2.Samples.TransactionalAuth/Box.V2.Samples.TransactionalAuth.csproj, Box.V2.Samples.TransactionalAuth/Program.cs, Box.V2.Samples.TransactionalAuth/Properties/AssemblyInfo.cs, Box.V2.Samples.TransactionalAuth/packages.config, Box.V2.TransactionalAuth/Box.V2.TransactionalAuth.csproj, Box.V2.TransactionalAuth/BoxTransactionalAuth.cs, Box.V2.TransactionalAuth/Properties/AssemblyInfo.cs, Box.V2.TransactionalAuth/TransactionalAuthRepository.cs, Box.V2.TransactionalAuth/app.config, Box.V2.TransactionalAuth/packages.config, Box.V2.sln, Box.V2/Box.V2.csproj, Box.V2/Config/Constants.cs, Box.V2/Models/BoxRestrictedTo.cs, Box.V2/Models/OAuthSession.cs, packages/repositories.config
Adding implementation, exchenges token.
Adding example project
=> Transactional auth

Box.V2.Samples.JWTAuth/Program.cs
=> Improperly Named Variable In JWTAuth Sample

Box.V2.Samples.Core.File.Upload/project.json
Hi Yang, 
Please check.
Thanks,
Pal.
=> New hire commit

Box.V2.Core/DotNetUtilities.cs, Box.V2.Core/project.json, Box.V2.Samples.Core.File.Upload/project.json, Box.V2/Box.V2.csproj, Box.V2/Managers/BoxFilesManager.cs, Box.V2/Models/BoxSessionEndpoint.cs, Box.V2/Models/BoxSessionParts.cs, Box.V2/Models/BoxSessionUploadStatus.cs
- New SDK function to get status of upload session
- Utility function in DotNetCore to get SHA hash
- Minor refactoring
=> Mupload p1

Box.V2.Test.Integration/BoxFilesManagerTestIntegration.cs
Creating file in memory for Integration tests
=> Creating file in memory for Integration tests

Box.V2.Core/project.json, Box.V2.Test.Integration/BoxFilesManagerTestIntegration.cs, Box.V2/Box.V2.csproj, Box.V2/Extensions/UriExtensions.cs, Box.V2/Managers/BoxFilesManager.cs, Box.V2/Models/BoxSessionParts.cs, Box.V2/Utility/Helper.cs
- Marker and limit options in List Parts function
- Updated Integration tests to validate marker and limit
=> List parts update

Box.V2.Test.Integration/BoxFilesManagerTestIntegration.cs, Box.V2/Managers/BoxFilesManager.cs, Box.V2/Utility/CrossPlatform.cs, Box.V2/Utility/Helper.cs
- Multi upload utility function
=> Multiupload utility function

Box.V2.Test.Integration/BoxFilesManagerTestIntegration.cs, Box.V2/Managers/BoxFilesManager.cs, Box.V2/Utility/CrossPlatform.cs
- Utility function can be called using the portable library as well
=> Multiupload utility portable library

Box.V2/Config/Constants.cs
=> SDK should use api.box.com for the /token API

Box.V2.JWTAuth/BoxJWTAuth.cs
=> Throw exception on private key read error

Box.V2/Models/BoxFile.cs
=> Added Extension field

Box.V2/Extensions/BoxResponseExtensions.cs
=> Handle the UploadFile conflict exception correctly

Box.V2.Test.Integration/Box.V2.Test.Integration.csproj, Box.V2.Test.Integration/BoxTokenExchangeTestIntegration.cs, Box.V2/Auth/Token/TokenExchange.cs
1. Scopes support
2. Integration test
=> Token exchange with scopes

Box.V2.JWTAuth/Box.V2.JWTAuth.nuspec, Box.V2.JWTAuth/Properties/AssemblyInfo.cs, Box.V2/Box.V2.nuspec, Box.V2/Config/BoxConfig.cs, Box.V2/Utility/AssemblyInfo.cs
1. JWTAuth to 1.3.3
2. Box.V2 to 2.15.6
#297
=> Fixed the version binding under azure functions

Box.V2/Box.V2.csproj, Box.V2/Converter/BoxItemConverter.cs, Box.V2/Models/BoxFolderEventSource.cs
This fixes folder event sources getting converted from the response object.
=> Adding folder event source to converter (fixes #345)

Box.V2.Core/Box.V2.Core.csproj, Box.V2.Samples.Core.AppUser.Create/Program.cs, Box.V2.Test.Integration/BoxUsersManagerTestIntegration.cs, Box.V2/Managers/BoxUsersManager.cs, Box.V2/Models/Request/BoxUserRequest.cs
Missing JWTAuth cs files into Core
=> App User External Id Support

Box.V2.Test.Integration/BoxMetadataManagerTestIntegration.cs, Box.V2/Managers/BoxMetadataManager.cs, Box.V2/Models/BoxEnums.cs, Box.V2/Models/BoxMetadataTemplateUpdate.cs
editEnumOption,
removeField,
removeEnumOption
=> Added 3 new MD OP

Box.V2.Core/Box.V2.Core.csproj, Box.V2.Test.Integration/BoxFilesManagerTestIntegration.cs, Box.V2/Box.V2.csproj, Box.V2/Managers/BoxFilesManager.cs, Box.V2/Utility/BoxProgess.cs
Updated the Box.V2.Core Version
=> BoxProgress class for better handling in the future

Box.V2.Core/Box.V2.Core.csproj, Box.V2.Core/Box.V2.Core.nuspec, Box.V2.Samples.Core.File.Upload/Program.cs, Box.V2/Box.V2.nuspec, Box.V2/Utility/AssemblyInfo.cs
=> v3.1.0 release

README.md
Examples for getting enterprise users and getting user folder items
=> Authentication docs update. 

Box.V2.Test.Integration/BoxEventsManagerTestIntegration.cs, Box.V2.Test.Integration/BoxResourceManagerTestIntegration.cs, Box.V2/Managers/BoxEventsManager.cs
Ran BoxEventsManagerTestIntegration with new datetime format and passed tests and retrieved same results from previous datetime format
=> Enterprise events datetime format

Box.V2.Test.Integration/BoxEventsManagerTestIntegration.cs, Box.V2/Managers/BoxEventsManager.cs
put back encoding if not null and added two additional test cases
1.) if one optional field for time is null
2.) if both optional fields for time is null
=> Fix eventsmanager mistake

Box.V2.Test.Integration/BoxFilesManagerTestIntegration.cs, Box.V2.Test.Integration/BoxResourceManagerTestIntegration.cs, Box.V2/Managers/BoxFilesManager.cs, Box.V2/Models/BoxFile.cs
Updated functionality for upload file version using session
Test case for UploadFileVersionUsingSessionAsync()
Updated BoxFile model to include BoxFileVersion
=> Chunk upload file version

Box.V2.Test.Integration/BoxFilesManagerTestIntegration.cs, Box.V2/Managers/BoxFilesManager.cs
Hey Yang, I broke the test method out into a separate utility method test because I didn't want to clog UploadFileInSession_AbortRequest_FileNotCommmited() with all the part size number tests. Let me know what you think!
=> fix for get number of parts

Box.V2.Test.Integration/BoxFoldersManagerTestIntegration.cs, Box.V2/Models/BoxFolder.cs
=> added missing parameters to BoxFolder model

Box.V2.Test.Integration/BoxMetadataManagerTestIntegration.cs, Box.V2.Test.Integration/BoxResourceManagerTestIntegration.cs, Box.V2/Config/Constants.cs, Box.V2/Converter/BoxItemConverter.cs, Box.V2/Managers/BoxMetadataManager.cs, Box.V2/Models/BoxMetadataTemplate.cs
=> Metadata template id update

Box.V2/Config/Constants.cs
=> Added constants for event types

Box.V2/Models/Request/BoxCollaborationRequest.cs
=> Add expires_at parameter to Collaboration request params

Box.V2/Models/BoxEntity.cs, Box.V2/Models/BoxFileEventSource.cs, Box.V2/Models/BoxFolderEventSource.cs
=> Fix event source subclass property overrides

Box.V2/Request/HttpRequestHandler.cs
=> Catch exceptions when attempting to set TLSv1.2 protocol

Box.V2.Core/Box.V2.Core.csproj, Box.V2/Box.V2.csproj
=> Generate method docs for nuget package

Box.V2.Test/BoxEventsManagerTest.cs, Box.V2/Box.V2.csproj, Box.V2/Converter/BoxItemConverter.cs, Box.V2/Models/BoxWebLinkEventSource.cs
=> Add WebLink event source class

Box.V2.Test.Integration/BoxFilesManagerTestIntegration.cs, Box.V2.Test/BoxFilesManagerTest.cs, Box.V2/Managers/BoxFilesManager.cs
=> Add correct method for retrieving file collaborations

Box.V2.Test/BoxUsersManagerTest.cs, Box.V2/Models/BoxUser.cs
=> Add missing fields to User model

Box.V2/JWTAuth/BoxJWTAuth.cs
Fixes #544
Motivation: I would like to be able to add custom IRequestHandlers to GetToken requests, so that I would be able to, e.g. log some relevant information
=> Accept IBoxService in BoxJWTAuth constructor

Box.V2.Test/BoxFilesManagerTest.cs, Box.V2/Config/Constants.cs, Box.V2/Managers/BoxFilesManager.cs
https://github.com/box/box-windows-sdk-v2/issues/547
=> GetThumbnailAsync - add endpoint parameter (jpg/png)

Box.V2.Test/BoxUsersManagerTest.cs, Box.V2/Wrappers/BoxRequest.cs
=> Encode query parameters

README.md
Added missing semicolon to example to find specific user.
=> README.md Minor Syntax Correction

Box.V2.Test/BoxFoldersManagerTest.cs, Box.V2/Managers/BoxFoldersManager.cs
=> Allow sorting folder items

Box.V2.Test/BoxSearchManagerTest.cs, Box.V2/Managers/BoxSearchManager.cs, docs/search.md
=> Allow size ranges greater than 2GB in search method

Box.V2.Test/BoxUsersManagerTest.cs, Box.V2/Models/Request/BoxUserRequest.cs
=> Add ability to restrict external collaboration for a user

Box.V2.Test/BoxFilesManagerTest.cs, Box.V2.Test/BoxFoldersManagerTest.cs, Box.V2/Models/BoxFile.cs, Box.V2/Models/BoxFolder.cs
=> Add missing fields to file and folder models

Box.V2.Test/BoxEventsManagerTest.cs, Box.V2/Models/BoxEnterpriseEvent.cs
Adding support for action_by field on Enterprise Events.
=> Support for action_by field on enterprise events

Box.V2.Test.Integration/BoxUsersManagerTestIntegration.cs, Box.V2.Test/BoxUsersManagerTest.cs, Box.V2/Managers/BoxUsersManager.cs
This overload for GetUserInformationAsync() adds the optional field for retrieving user information.
=> Added overload for GetUserInformationAsync()

docs/tasks.md
Added a new sample variant for task assignment to include updating the message
=> Add new code sample for task assignment

Box.V2.Test/BoxFoldersManagerTest.cs, Box.V2/Models/BoxFile.cs, Box.V2/Models/BoxFolder.cs, Box.V2/Models/BoxItem.cs, CHANGELOG.md
Added `TrashedAt` field to `BoxItem`. Issue at #628.
=> Add  `TrashedAt` field to `BoxItem` (#628)

Box.V2.Test/BoxResourceManagerTest.cs, Box.V2.Test/BoxStoragePoliciesManagerTest.cs, Box.V2.Test/BoxTasksManagerTest.cs, Box.V2/Config/Constants.cs
=> Fix unit tests

Box.V2.Test/BoxUsersManagerTest.cs, Box.V2/Models/BoxNotificationEmail.cs, Box.V2/Models/BoxNotificationEmailField.cs, Box.V2/Models/BoxUser.cs, Box.V2/Models/Request/BoxUserRequest.cs, CHANGELOG.md
Add ability to get and set a notification email address for a user #639
=> Add ability to get and set a notification email address for a user

Box.V2.Test/BoxFilesManagerTest.cs, Box.V2/Models/BoxFile.cs, Box.V2/Models/BoxFileVersion.cs, CHANGELOG.md
Added the uploader display name field to the `BoxFile` and `BoxFileVersion` models
=> Add support for the uploader display name field for Files and File Versions

Box.V2.Test/BoxFilesManagerTest.cs, Box.V2.Test/BoxFoldersManagerTest.cs, Box.V2/Models/BoxClassification.cs, Box.V2/Models/BoxFile.cs, Box.V2/Models/BoxFolder.cs, CHANGELOG.md
Added classification field for `BoxFile` and `BoxFolder`.
=> Add support for the classification field for Files and Folders

docs/users.md
We changed the ID of this endpoint in the dev docs and therefore the samples need new IDs as well.
=>  Update sample tag for transfer folder

Box.V2.Test/BoxGroupsManagerTest.cs, Box.V2/Managers/BoxGroupsManager.cs, CHANGELOG.md, docs/groups.md
Added support for the filter term when getting a list of groups.
=> Add support for filtering when getting Groups

Box.V2.Test/BoxRetentionPoliciesManagerTest.cs, Box.V2/Managers/BoxRetentionPoliciesManager.cs, Box.V2/Models/BoxEnums.cs, Box.V2/Models/BoxRetentionPolicy.cs, Box.V2/Utility/Helper.cs, CHANGELOG.md, docs/retention-policies.md
Add filter params to `BoxRetentionPoliciesManager.GetFileVersionRetentionsAsync()`
=> Add filter fields to get file version retentions

Box.V2/JWTAuth/BoxJWTAuth.cs
=> Fix exp in jwt

Box.V2.Test/Box.V2.Test.csproj, Box.V2.Test/BoxFileRequestsManagerTest.cs, Box.V2.Test/BoxResourceManagerTest.cs, Box.V2.Test/Fixtures/BoxFileRequest/CopyFileRequest200.json, Box.V2.Test/Fixtures/BoxFileRequest/GetFileRequest200.json, Box.V2.Test/Fixtures/BoxFileRequest/UpdateFileRequest200.json, Box.V2/Box.V2.csproj, Box.V2/BoxClient.cs, Box.V2/Config/BoxConfig.cs, Box.V2/Config/Constants.cs, Box.V2/Config/IBoxConfig.cs, Box.V2/Converter/BoxItemConverter.cs, Box.V2/IBoxClient.cs, Box.V2/Managers/BoxFileRequestsManager.cs, Box.V2/Managers/IBoxFileRequestsManager.cs, Box.V2/Models/BoxFileRequestObject.cs, Box.V2/Models/Request/BoxFileRequestCopyRequest.cs, Box.V2/Models/Request/BoxFileRequestUpdateRequest.cs
=> feat: add file request api

Box.V2/BoxClient.cs, Box.V2/Config/BoxConfig.cs, Box.V2/Config/BoxConfigBuilder.cs, Box.V2/Config/IBoxConfig.cs, Box.V2/JWTAuth/BoxJWTAuth.cs, Box.V2/Request/HttpRequestHandler.cs
=> feat: add configurable Timeout for BoxClient

build/bump_version.ps1, build/draft_release.ps1, build/ensure_git_clean.ps1, build/publish_core_package.ps1, build/publish_framework_package.ps1, build/publish_release.ps1
Fixed several issues found during testing with the release VM. Also changed the approach to creating the release draft first and attaching artifacts to it as soon as they are created to avoid storing artifacts between steps.
=> chore: release script changes

Box.V2.Core/Box.V2.Core.csproj, Box.V2/Box.V2.nuspec, Box.V2/Utility/AssemblyInfo.cs, CHANGELOG.md
Bumping version files for the next release! v4.3.0
=> chore: release v4.3.0

Box.V2/Request/HttpRequestHandler.cs
Fix for #710. When an exception is thrown for a stream response and the response is not properly disposed of, the connection is not properly closed and there is a possibility of starving the connection pool.
=> fix: properly dispose response on exception to prevent connection pool starvation

docs/files.md
=> docs: added documentation on using chunked uploads

Box.V2.Core/Box.V2.Core.csproj, Box.V2/Box.V2.nuspec, Box.V2/Utility/AssemblyInfo.cs, CHANGELOG.md
Bumping version files for the next release! v4.4.0
=> chore: release v4.4.0

docs/folders.md
Async method must be awaited when creating a folder
=> docs: Await folder creation

Box.V2.Test/BoxSignRequestsManagerTest.cs, Box.V2.Test/Fixtures/BoxSignRequest/CancelSignRequest200.json, Box.V2.Test/Fixtures/BoxSignRequest/CreateSignRequest200.json, Box.V2.Test/Fixtures/BoxSignRequest/GetAllSignRequests200.json, Box.V2.Test/Fixtures/BoxSignRequest/GetSignRequest200.json, Box.V2/Models/BoxSignRequestSigner.cs
=> feat: Add `content-type` field to sign request

Box.V2.Core/Box.V2.Core.csproj, Box.V2/Box.V2.nuspec, Box.V2/Utility/AssemblyInfo.cs, CHANGELOG.md
Bumping version files for the next release! v4.5.0
=> chore: release v4.5.0

Box.V2.Test/BoxSignRequestsManagerTest.cs, Box.V2.Test/Fixtures/BoxSignRequest/CancelSignRequest200.json, Box.V2.Test/Fixtures/BoxSignRequest/CreateSignRequest200.json, Box.V2.Test/Fixtures/BoxSignRequest/GetAllSignRequests200.json, Box.V2.Test/Fixtures/BoxSignRequest/GetSignRequest200.json, Box.V2/Models/BoxSignRequest.cs, Box.V2/Models/BoxSignRequestSigner.cs, Box.V2/Models/Request/BoxSignRequestCreateRequest.cs
=> feat: Add `redirect_url` and `declined_redirect_url` to Sign Request

Box.V2.Test.Integration/BoxSignRequestManagerIntegrationTest.cs, Box.V2.Test.Integration/BoxWebhookManagerIntegrationTest.cs, Box.V2.Test.Integration/Configuration/Commands/DisposableCommands/CreateSignRequestCommand.cs, Box.V2.Test.Integration/Configuration/Commands/DisposableCommands/CreateWebhookCommand.cs, Box.V2.Test.Integration/Configuration/IntegrationTestBase.cs
=> chore: Add sign request webhook

Box.V2.Core/Box.V2.Core.csproj, Box.V2/Box.V2.nuspec, Box.V2/Utility/AssemblyInfo.cs, CHANGELOG.md
Bumping version files for the next release! v4.6.0
=> chore: release v4.6.0

Box.V2.Core/Box.V2.Core.csproj, Box.V2/Box.V2.nuspec, Box.V2/Utility/AssemblyInfo.cs, CHANGELOG.md
Bumping version files for the next release! v5.1.0
=> chore: release v5.1.0

Box.V2.Test.Integration/BoxFolderManagerIntegrationTest.cs, Box.V2.Test.Integration/Configuration/IntegrationTestBase.cs, Box.V2.Test/BoxFoldersManagerTest.cs, Box.V2/Box.V2.csproj, Box.V2/Managers/BoxFoldersManager.cs, Box.V2/Managers/BoxSharedItemsManager.cs, Box.V2/Managers/IBoxFoldersManager.cs, Box.V2/Utility/SharedLinkUtils.cs
=> feat: add shared link support to `GetFolderItemsAsync`

Box.V2.Core/Box.V2.Core.csproj, Box.V2/Box.V2.nuspec, Box.V2/Utility/AssemblyInfo.cs, CHANGELOG.md
Bumping version files for the next release! v5.2.0
=> chore: release v5.2.0

docs/events.md
=> docs: Update event documentation

Box.V2.Core/Box.V2.Core.csproj, Box.V2/Box.V2.nuspec, Box.V2/Utility/AssemblyInfo.cs, CHANGELOG.md
Bumping version files for the next release! v5.2.1
=> chore: release v5.2.1

Box.V2.Core/Box.V2.Core.csproj, Box.V2/Box.V2.nuspec, Box.V2/Utility/AssemblyInfo.cs, CHANGELOG.md
Bumping version files for the next release! v5.2.2
=> chore: release v5.2.2

Box.V2.Core/Box.V2.Core.csproj, Box.V2/Box.V2.nuspec, Box.V2/Utility/AssemblyInfo.cs, CHANGELOG.md
Bumping version files for the next release! v5.3.0
=> chore: release v5.3.0

Box.V2.Core/Box.V2.Core.csproj, Box.V2/Box.V2.nuspec, Box.V2/Utility/AssemblyInfo.cs, CHANGELOG.md
Bumping version files for the next release! v5.4.0
=> chore: release v5.4.0

Box.V2.Core/Box.V2.Core.csproj, Box.V2/Box.V2.nuspec, Box.V2/Utility/AssemblyInfo.cs, CHANGELOG.md
Bumping version files for the next release! v5.5.0
=> chore: release v5.5.0

Box.V2.Test.Integration/BoxSignRequestManagerIntegrationTest.cs, Box.V2.Test/BoxSignRequestsManagerTest.cs, Box.V2.Test/Fixtures/BoxSignRequest/CancelSignRequest200.json, Box.V2.Test/Fixtures/BoxSignRequest/CreateSignRequest200.json, Box.V2.Test/Fixtures/BoxSignRequest/GetAllSignRequests200.json, Box.V2.Test/Fixtures/BoxSignRequest/GetSignRequest200.json, Box.V2/Models/BoxSignRequestSigner.cs
=> feat: Support `iframeable_embed_url` for sign request

Box.V2.Core/Box.V2.Core.csproj, Box.V2/Box.V2.nuspec, Box.V2/Utility/AssemblyInfo.cs, CHANGELOG.md
Bumping version files for the next release! v5.6.0
=> chore: release v5.6.0

Box.V2.Core/Box.V2.Core.csproj, Box.V2/Box.V2.nuspec, Box.V2/Utility/AssemblyInfo.cs, CHANGELOG.md
Bumping version files for the next release! v5.7.0
=> chore: release v5.7.0

Box.V2.Core/Box.V2.Core.csproj, Box.V2/Box.V2.nuspec, Box.V2/Utility/AssemblyInfo.cs, CHANGELOG.md
Bumping version files for the next release! v5.7.1
=> chore: release v5.7.1

Box.V2.Core/Box.V2.Core.csproj, Box.V2/Box.V2.nuspec, Box.V2/Utility/AssemblyInfo.cs, CHANGELOG.md
Bumping version files for the next release! v5.8.0
=> chore: release v5.8.0
